<?php

namespace Cgit\Schema\PostType;

class JobVacancy extends PostType
{
    /**
     * Post type parameters
     *
     * @var array
     */
    protected $typeArgs = [
        'has_archive' => true,
        'menu_icon' => 'dashicons-businessman',
        'public' => true,
        'supports' => [
            'title',
            'editor',
            'thumbnail',
            'excerpt',
            'revisions',
            'page-attributes',
        ],
    ];

    /**
     * Custom field parameters
     *
     * @var array
     */
    protected $fieldArgs = [
        'fields' => [
            [
                'key' => 'cgit_wp_schema_job_heading_1',
                'name' => 'job_heading_1',
                'label' => 'Job details',
                'type' => 'message',
                'message' => 'Enter as much information as you can about the job vacancy. If you enter a maximum salary, the mininum salary will be the base salary. The unique identifier is an optional number or code that you might use to identify the vacancy.',
            ],

            [
                'key' => 'cgit_wp_schema_job_salary',
                'name' => 'job_salary',
                'label' => 'Base salary',
                'type' => 'number',
                'wrapper' => ['width' => 25],
            ],

            [
                'key' => 'cgit_wp_schema_job_max_salary',
                'name' => 'job_max_salary',
                'label' => 'Maximum salary (optional)',
                'type' => 'number',
                'wrapper' => ['width' => 25],
            ],

            [
                'key' => 'cgit_wp_schema_job_currency',
                'name' => 'job_currency',
                'label' => 'Currency',
                'type' => 'select',
                'default_value' => 'GBP',
                'wrapper' => ['width' => 25],
                'choices' => [
                    'XUA' => 'ADB Unit of Account',
                    'AFN' => 'Afghani',
                    'DZD' => 'Algerian Dinar',
                    'ARS' => 'Argentine Peso',
                    'AMD' => 'Armenian Dram',
                    'AWG' => 'Aruban Florin',
                    'AUD' => 'Australian Dollar',
                    'AZN' => 'Azerbaijanian Manat',
                    'BSD' => 'Bahamian Dollar',
                    'BHD' => 'Bahraini Dinar',
                    'THB' => 'Baht',
                    'PAB' => 'Balboa',
                    'BBD' => 'Barbados Dollar',
                    'BYR' => 'Belarussian Ruble',
                    'BZD' => 'Belize Dollar',
                    'BMD' => 'Bermudian Dollar',
                    'VEF' => 'Bolivar',
                    'BOB' => 'Boliviano',
                    'BRL' => 'Brazilian Real',
                    'BND' => 'Brunei Dollar',
                    'BGN' => 'Bulgarian Lev',
                    'BIF' => 'Burundi Franc',
                    'CVE' => 'Cabo Verde Escudo',
                    'CAD' => 'Canadian Dollar',
                    'KYD' => 'Cayman Islands Dollar',
                    'XOF' => 'CFA Franc BCEAO',
                    'XAF' => 'CFA Franc BEAC',
                    'XPF' => 'CFP Franc',
                    'CLP' => 'Chilean Peso',
                    'COP' => 'Colombian Peso',
                    'KMF' => 'Comoro Franc',
                    'CDF' => 'Congolese Franc',
                    'BAM' => 'Convertible Mark',
                    'NIO' => 'Cordoba Oro',
                    'CRC' => 'Costa Rican Colon',
                    'CUP' => 'Cuban Peso',
                    'CZK' => 'Czech Koruna',
                    'GMD' => 'Dalasi',
                    'DKK' => 'Danish Krone',
                    'MKD' => 'Denar',
                    'DJF' => 'Djibouti Franc',
                    'STD' => 'Dobra',
                    'DOP' => 'Dominican Peso',
                    'VND' => 'Dong',
                    'XCD' => 'East Caribbean Dollar',
                    'EGP' => 'Egyptian Pound',
                    'SVC' => 'El Salvador Colon',
                    'ETB' => 'Ethiopian Birr',
                    'EUR' => 'Euro',
                    'FKP' => 'Falkland Islands Pound',
                    'FJD' => 'Fiji Dollar',
                    'HUF' => 'Forint',
                    'GHS' => 'Ghana Cedi',
                    'GIP' => 'Gibraltar Pound',
                    'HTG' => 'Gourde',
                    'PYG' => 'Guarani',
                    'GNF' => 'Guinea Franc',
                    'GYD' => 'Guyana Dollar',
                    'HKD' => 'Hong Kong Dollar',
                    'UAH' => 'Hryvnia',
                    'ISK' => 'Iceland Krona',
                    'INR' => 'Indian Rupee',
                    'IRR' => 'Iranian Rial',
                    'IQD' => 'Iraqi Dinar',
                    'JMD' => 'Jamaican Dollar',
                    'JOD' => 'Jordanian Dinar',
                    'KES' => 'Kenyan Shilling',
                    'PGK' => 'Kina',
                    'LAK' => 'Kip',
                    'HRK' => 'Kuna',
                    'KWD' => 'Kuwaiti Dinar',
                    'MWK' => 'Kwacha',
                    'AOA' => 'Kwanza',
                    'MMK' => 'Kyat',
                    'GEL' => 'Lari',
                    'LBP' => 'Lebanese Pound',
                    'ALL' => 'Lek',
                    'HNL' => 'Lempira',
                    'SLL' => 'Leone',
                    'LRD' => 'Liberian Dollar',
                    'LYD' => 'Libyan Dinar',
                    'SZL' => 'Lilangeni',
                    'LSL' => 'Loti',
                    'MGA' => 'Malagasy Ariary',
                    'MYR' => 'Malaysian Ringgit',
                    'MUR' => 'Mauritius Rupee',
                    'MXN' => 'Mexican Peso',
                    'MXV' => 'Mexican Unidad de Inversion (UDI)',
                    'MDL' => 'Moldovan Leu',
                    'MAD' => 'Moroccan Dirham',
                    'MZN' => 'Mozambique Metical',
                    'BOV' => 'Mvdol',
                    'NGN' => 'Naira',
                    'ERN' => 'Nakfa',
                    'NAD' => 'Namibia Dollar',
                    'NPR' => 'Nepalese Rupee',
                    'ANG' => 'Netherlands Antillean Guilder',
                    'ILS' => 'New Israeli Sheqel',
                    'TWD' => 'New Taiwan Dollar',
                    'NZD' => 'New Zealand Dollar',
                    'BTN' => 'Ngultrum',
                    'KPW' => 'North Korean Won',
                    'NOK' => 'Norwegian Krone',
                    'PEN' => 'Nuevo Sol',
                    'MRO' => 'Ouguiya',
                    'TOP' => 'Pa’anga',
                    'PKR' => 'Pakistan Rupee',
                    'MOP' => 'Pataca',
                    'CUC' => 'Peso Convertible',
                    'UYU' => 'Peso Uruguayo',
                    'PHP' => 'Philippine Peso',
                    'GBP' => 'Pound Sterling',
                    'BWP' => 'Pula',
                    'QAR' => 'Qatari Rial',
                    'GTQ' => 'Quetzal',
                    'ZAR' => 'Rand',
                    'OMR' => 'Rial Omani',
                    'KHR' => 'Riel',
                    'RON' => 'Romanian Leu',
                    'MVR' => 'Rufiyaa',
                    'IDR' => 'Rupiah',
                    'RUB' => 'Russian Ruble',
                    'RWF' => 'Rwanda Franc',
                    'SHP' => 'Saint Helena Pound',
                    'SAR' => 'Saudi Riyal',
                    'XDR' => 'SDR (Special Drawing Right)',
                    'RSD' => 'Serbian Dinar',
                    'SCR' => 'Seychelles Rupee',
                    'SGD' => 'Singapore Dollar',
                    'SBD' => 'Solomon Islands Dollar',
                    'KGS' => 'Som',
                    'SOS' => 'Somali Shilling',
                    'TJS' => 'Somoni',
                    'SSP' => 'South Sudanese Pound',
                    'LKR' => 'Sri Lanka Rupee',
                    'XSU' => 'Sucre',
                    'SDG' => 'Sudanese Pound',
                    'SRD' => 'Surinam Dollar',
                    'SEK' => 'Swedish Krona',
                    'SYP' => 'Syrian Pound',
                    'BDT' => 'Taka',
                    'WST' => 'Tala',
                    'TZS' => 'Tanzanian Shilling',
                    'KZT' => 'Tenge',
                    'TTD' => 'Trinidad and Tobago Dollar',
                    'MNT' => 'Tugrik',
                    'TND' => 'Tunisian Dinar',
                    'TRY' => 'Turkish Lira',
                    'TMT' => 'Turkmenistan New Manat',
                    'AED' => 'UAE Dirham',
                    'UGX' => 'Uganda Shilling',
                    'CLF' => 'Unidad de Fomento',
                    'COU' => 'Unidad de Valor Real',
                    'UYI' => 'Uruguay Peso en Unidades Indexadas (URUIURUI)',
                    'USD' => 'US Dollar',
                    'USN' => 'US Dollar (Next day)',
                    'UZS' => 'Uzbekistan Sum',
                    'VUV' => 'Vatu',
                    'CHE' => 'WIR Euro',
                    'CHW' => 'WIR Franc',
                    'KRW' => 'Won',
                    'YER' => 'Yemeni Rial',
                    'JPY' => 'Yen',
                    'CNY' => 'Yuan Renminbi',
                    'ZMW' => 'Zambian Kwacha',
                    'ZWL' => 'Zimbabwe Dollar',
                    'PLN' => 'Zloty',
                ],
            ],

            [
                'key' => 'cgit_wp_schema_job_salary_unit',
                'name' => 'job_salary_unit',
                'label' => 'Salary unit',
                'type' => 'select',
                'default_value' => 'YEAR',
                'wrapper' => ['width' => 25],
                'choices' => [
                    'HOUR' => 'Hour',
                    'DAY' => 'Day',
                    'WEEK' => 'Week',
                    'MONTH' => 'Month',
                    'YEAR' => 'Year',
                ],
            ],

            [
                'key' => 'cgit_wp_schema_job_employment_type',
                'name' => 'job_employment_type',
                'label' => 'Employment type',
                'type' => 'select',
                'default_value' => 'FULL_TIME',
                'wrapper' => ['width' => 25],
                'choices' => [
                    'FULL_TIME' => 'Full time',
                    'PART_TIME' => 'Part time',
                    'CONTRACTOR' => 'Contractor',
                    'TEMPORARY' => 'Temporary',
                    'INTERN' => 'Intern',
                    'VOLUNTEER' => 'Volunteer',
                    'PER_DIEM' => 'Per diem',
                    'OTHER' => 'Other',
                ],
            ],

            [
                'key' => 'cgit_wp_schema_job_id',
                'name' => 'job_id',
                'label' => 'Unique identifier (optional)',
                'type' => 'text',
                'wrapper' => ['width' => 25],
            ],

            [
                'key' => 'cgit_wp_schema_job_closing_date',
                'name' => 'job_closing_date',
                'label' => 'Closing date (optional)',
                'type' => 'date_picker',
                'wrapper' => ['width' => 25],
                'return_format' => 'Y-m-d',
            ],

            [
                'key' => 'cgit_wp_schema_job_heading_2',
                'name' => 'job_heading_2',
                'label' => 'Job location',
                'type' => 'message',
                'message' => 'Enter as much information as you can about the location of the job vacancy. Each vacancy should at least have a country.',
            ],

            [
                'key' => 'cgit_wp_schema_job_street_address',
                'name' => 'job_street_address',
                'label' => 'Street address',
                'type' => 'text',
                'wrapper' => ['width' => 50],
            ],

            [
                'key' => 'cgit_wp_schema_job_address_locality',
                'name' => 'job_address_locality',
                'label' => 'Town or city',
                'type' => 'text',
                'wrapper' => ['width' => 50],
            ],

            [
                'key' => 'cgit_wp_schema_job_address_region',
                'name' => 'job_address_region',
                'label' => 'County or state',
                'type' => 'text',
                'wrapper' => ['width' => 50],
            ],

            [
                'key' => 'cgit_wp_schema_job_postal_code',
                'name' => 'job_postal_code',
                'label' => 'Postal code',
                'type' => 'text',
                'wrapper' => ['width' => 50],
            ],

            [
                'key' => 'cgit_wp_schema_job_address_country',
                'name' => 'job_address_country',
                'label' => 'Country',
                'type' => 'text',
                'wrapper' => ['width' => 50],
            ],
        ],
    ];

    /**
     * Initialization
     *
     * @return void
     */
    protected function init()
    {
        $this->labels('Job Vacancy', 'Job Vacancies');
    }
}
